In [1]:
import numpy as np
A = np.array([[56.0, 0.0, 4.4, 68.0],[1.2, 104.0, 52.0, 8.0],[1.8, 135.0, 99.0, 0.9]])
print (A)

[[ 56.    0.    4.4  68. ]
 [  1.2 104.   52.    8. ]
 [  1.8 135.   99.    0.9]]


In [3]:
cal =A.sum(axis=0)
print (cal)

[ 59.  239.  155.4  76.9]


In [4]:
percentage = 100*A/cal.reshape(1,4)
print (percentage)

[[94.91525424  0.          2.83140283 88.42652796]
 [ 2.03389831 43.51464435 33.46203346 10.40312094]
 [ 3.05084746 56.48535565 63.70656371  1.17035111]]


In [11]:
a= np.random.randn(5,1)
print (a)

[[ 0.06694826]
 [ 1.4802584 ]
 [-1.75691051]
 [-1.16397362]
 [ 0.5910651 ]]


In [12]:
print (a.shape)


(5, 1)


In [13]:
print(a.T)

[[ 0.06694826  1.4802584  -1.75691051 -1.16397362  0.5910651 ]]


In [14]:
print (np.dot(a,a.T))

[[ 0.00448207  0.09910073 -0.11762211 -0.07792601  0.03957078]
 [ 0.09910073  2.19116493 -2.60068155 -1.72298174  0.87492908]
 [-0.11762211 -2.60068155  3.08673455  2.0449975  -1.03844849]
 [-0.07792601 -1.72298174  2.0449975   1.3548346  -0.68798419]
 [ 0.03957078  0.87492908 -1.03844849 -0.68798419  0.34935795]]


In [15]:
a = np.random.randn(3, 3)
b = np.random.randn(3, 1)
c = a*b

In [16]:
c

array([[-1.03243637,  2.56245967, -0.23772871],
       [-0.32599017,  0.12525073,  1.29499084],
       [ 0.00421165, -0.01626748, -0.01387619]])

In [17]:
a = np.random.randn(12288, 150) # a.shape = (12288, 150)
b = np.random.randn(150, 45) # b.shape = (150, 45)
c = np.dot(a,b)

In [18]:
c.shape

(12288, 45)

In [19]:
a = np.random.randn(4, 3) # a.shape = (4, 3)
b = np.random.randn(3, 2) # b.shape = (3, 2)
c = a*b

ValueError: operands could not be broadcast together with shapes (4,3) (3,2) 

In [20]:
a = np.random.randn(2, 3) # a.shape = (2, 3)
b = np.random.randn(2, 1) # b.shape = (2, 1)
c = a + b
c.shape

(2, 3)

In [23]:
a=np.random.randn(3,4)
b=np.random.randn(4,1)
for i in range(3):
  for j in range(4):
    c[i][j] = a[i][j] + b[j]
d=a+b.T
c==d

IndexError: list assignment index out of range

In [22]:
(b+c)*()